name: Bump Version and Create PR

on:
  push:
    branches:
      - main

jobs:
  version-bump:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Get current and next version
        id: version
        run: |
          csproj=$(find . -name '*.csproj' | head -n 1)
          echo "Using $csproj"

          version=$(grep -oPm1 '(?<=<Version>)[^<]+' "$csproj")
          echo "Current version: $version"

          IFS='.' read -r major minor patch <<< "$version"
          new_version="$major.$minor.$((patch + 1))"

          echo "New version: $new_version"

          echo "old=$version" >> "$GITHUB_OUTPUT"
          echo "new=$new_version" >> "$GITHUB_OUTPUT"
          echo "file=$csproj" >> "$GITHUB_OUTPUT"
          echo "branch=version-bump-v$new_version" >> "$GITHUB_OUTPUT"

      - name: Bump version
        run: |
          sed -i "s|<Version>${{ steps.version.outputs.old }}</Version>|<Version>${{ steps.version.outputs.new }}</Version>|" "${{ steps.version.outputs.file }}"

      - name: Commit and push changes
        run: |
          git checkout -b "${{ steps.version.outputs.branch }}"
          git add "${{ steps.version.outputs.file }}"
          git commit -m "chore: bump version to v${{ steps.version.outputs.new }}"
          git push origin "${{ steps.version.outputs.branch }}"

      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          PR_BODY="Automated version bump after merge to main.

**Old version:** v${{ steps.version.outputs.old }}
**New version:** v${{ steps.version.outputs.new }}"

          gh pr create \
            --title "chore: bump version to v${{ steps.version.outputs.new }}" \
            --body "$PR_BODY" \
            --base main \
            --head "${{ steps.version.outputs.branch }}"

