name: Publish

on:
  push:
    branches:
      - main

jobs:
  bump-version:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Bump <Version> in .csproj
        shell: pwsh
        run: |
          $csproj = Get-ChildItem -Recurse -Filter *.csproj | Select-Object -First 1
          $content = Get-Content $csproj.FullName -Raw

          if ($content -notmatch '<Version>(\d+)\.(\d+)\.(\d+)</Version>') {
              Write-Error "No <Version> tag found."
              exit 1
          }

          $major = [int]$matches[1]
          $minor = [int]$matches[2]
          $patch = [int]$matches[3]
          $newPatch = $patch + 1
          $newVersion = "$major.$minor.$newPatch"

          Write-Host "Old version: $major.$minor.$patch"
          Write-Host "New version: $newVersion"

          $newContent = $content -replace "<Version>$major\.$minor\.$patch</Version>", "<Version>$newVersion</Version>"
          Set-Content $csproj.FullName $newContent

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git checkout -b "version-bump-v$major.$minor.$newPatch"
          git add .
          git commit -m "chore: bump version to v$newVersion"
          git push origin "version-bump-v$major.$minor.$newPatch"

      - name: Create pull request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Bump version to v${{ env.newVersion }}"
          body: |
            Automated version bump after merge to main.

            **Old version**: v${{ env.major }}.${{ env.minor }}.${{ env.patch }}
            **New version**: v${{ env.newVersion }}
          base: main
          branch: version-bump-v${{ env.newVersion }}

