name: Publish

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  bump-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Bump <Version> in .csproj
        id: bump_version
        shell: pwsh
        run: |
          $csproj = Get-ChildItem -Recurse -Filter *.csproj | Select-Object -First 1
          $lines = Get-Content $csproj.FullName
          $newLines = @()
          $versionFound = $false

          foreach ($line in $lines) {
            if ($line -match '<Version>(\d+)\.(\d+)\.(\d+)</Version>') {
              $major = [int]$matches[1]
              $minor = [int]$matches[2]
              $patch = [int]$matches[3] + 1
              $newVersion = "$major.$minor.$patch"
              $newLine = "<Version>$newVersion</Version>"
              $newLines += $newLine
              $versionFound = $true
              echo "new_version=$newVersion" >> $env:GITHUB_ENV
              echo "version_bumped=true" >> $env:GITHUB_ENV
            } else {
              $newLines += $line
            }
          }

          if (-not $versionFound) {
            echo "No <Version> tag found."
            echo "version_bumped=false" >> $env:GITHUB_ENV
            exit 0
          }

          Set-Content -Path $csproj.FullName -Value $newLines

      - name: Commit and push changes
        if: env.version_bumped == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b version-bump-v${{ env.new_version }}
          git add *.csproj
          git commit -m "chore: bump version to v${{ env.new_version }}"
          git push origin version-bump-v${{ env.new_version }}

      - name: Create pull request
        if: env.version_bumped == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN || secrets.GITHUB_TOKEN }}
          title: "🔖 Version bump to v${{ env.new_version }}"
          body: |
            Automated version bump after merge to `main`.

            **New version:** `v${{ env.new_version }}`
          base: main
          branch: version-bump-v${{ env.new_version }}

