name: publish

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '*'
  release:
    types:
      - published

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true
  NuGetDirectory: ${{ github.workspace }}/nuget

defaults:
  run:
    shell: pwsh

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - run: dotnet pack --configuration Release --output ${{ env.NuGetDirectory }}

      - uses: actions/upload-artifact@v4
        with:
          name: nuget
          if-no-files-found: error
          retention-days: 7
          path: ${{ env.NuGetDirectory }}/*.nupkg

  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Bump <Version>
        id: bump_version
        run: |
          $csproj = Get-ChildItem -Recurse -Filter *.csproj | Select-Object -First 1
          $content = Get-Content $csproj.FullName -Raw
          $pattern = '<Version>(\d+)\.(\d+)\.(\d+)</Version>'

          if ($content -notmatch $pattern) {
            throw "No <Version> found."
          }

          $major = [int]$matches[1]
          $minor = [int]$matches[2]
          $patch = [int]$matches[3]
          $oldVersion = "$major.$minor.$patch"
          $newVersion = "$major.$minor." + ($patch + 1)

          $newContent = $content -replace $pattern, "<Version>$newVersion</Version>"
          Set-Content -Path $csproj.FullName -Value $newContent

          Write-Output "OLD_VERSION=$oldVersion" >> $env:GITHUB_ENV
          Write-Output "NEW_VERSION=$newVersion" >> $env:GITHUB_ENV

      - name: Commit and push version bump
        id: commit_push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          $branchName = "v-bump-$(Get-Date -Format 'yyyyMMddHHmmss')"
          git checkout -b $branchName
          git add *.csproj
          git commit -m "chore: bump version to $env:NEW_VERSION [skip ci]"
          git push https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/${{ github.repository }} $branchName
          echo "branchName=$branchName" >> $env:GITHUB_ENV

      - name: Create Pull Request
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          gh pr create \
            --title "chore: bump version to $NEW_VERSION" \
            --body "Automated version bump after merge to main.

Old version: v$OLD_VERSION
New version: v$NEW_VERSION" \
            --base main \
            --head "${branchName}"

      - name: Enable Auto-Merge
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          pr_url=$(gh pr view --json url -q .url)
          gh pr merge "$pr_url" --auto --squash

  publish:
    needs: deploy
    if: github.event_name == 'release' && github.event.action == 'published'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: nuget
          path: ${{ env.NuGetDirectory }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Publish NuGet package
        run: |
          foreach ($file in Get-ChildItem "${{ env.NuGetDirectory }}" -Recurse -Include *.nupkg) {
            dotnet nuget push $file `
              --api-key "${{ secrets.NUGET_APIKEY }}" `
              --source https://api.nuget.org/v3/index.json `
              --skip-duplicate
          }

