name: Publish

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

env:
  PROJECT_FILE: ./Sadie.API/Sadie.API.csproj

jobs:
  version-bump:
    name: Bump version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Get current version
        id: get_version
        run: |
          version=$(grep -oPm1 "(?<=<Version>)[^<]+" "$PROJECT_FILE")
          echo "Current version: $version"
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Bump patch version
        id: bump
        run: |
          old_version="${{ steps.get_version.outputs.version }}"
          IFS='.' read -r major minor patch <<< "$old_version"
          new_patch=$((patch + 1))
          new_version="$major.$minor.$new_patch"
          sed -i "s|<Version>$old_version</Version>|<Version>$new_version</Version>|" "$PROJECT_FILE"
          echo "old=$old_version" >> $GITHUB_OUTPUT
          echo "new=$new_version" >> $GITHUB_OUTPUT

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          branch_name="version-bump-v${{ steps.bump.outputs.new }}"
          git checkout -b "$branch_name"
          git add "$PROJECT_FILE"
          git commit -m "chore: bump version to v${{ steps.bump.outputs.new }}"
          git push https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/${{ github.repository }} "$branch_name"
          echo "branch_name=$branch_name" >> $GITHUB_ENV

      - name: Create pull request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          title: Bump version to v${{ steps.bump.outputs.new }}
          commit-message: chore: bump version to v${{ steps.bump.outputs.new }}
          body: >
            Automated version bump after merge to `main`.

            **Old version:** v${{ steps.bump.outputs.old }}
            **New version:** v${{ steps.bump.outputs.new }}
          base: main
          branch: ${{ env.branch_name }}

